### ISSUE TITLE
Workflow run fails when I use this action

### ISSUE THREAD

**Issue by srinucsedon** [eLco/setup-vault#9]
I tried to use the action with default steps below, however my job not even initializing if I use this action, if I comment this action, then workflow run successful.

I'm using ubuntu-latest github runner for my workflow.

steps:
  - uses: eLco/setup-vault@v1

Failure workflow run status:
Startup failure

Workflow file:
```
name: Greeting Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Vault CLI
      uses: eLco/setup-vault@v1

    - name: Verify Vault CLI installation
      run: vault --version
```

make a note that no indentation or syntax errors. If I use curl method to extract package and install using apt is working fine. However if I use this action, I'm having issue. Thanks.
